### ISSUE TITLE
How to use the loaded model?

### ISSUE THREAD

**Issue by monajalal** [KMnP/vise#1]
Could you please show some demo how to make use of this model?

<img width="1436" alt="Screen Shot 2021-07-14 at 12 28 05 PM" src="https://user-images.githubusercontent.com/1892917/125658315-8a247f56-4df2-449b-8994-0793b4ce8ed0.png">

**Comment by KMnP** [comment]
this is a ResNet-50 model, which depends on your use case, can be used for classification, detection or other tasks. Can you be more specific about your question?

**Comment by KMnP** [comment]
close this issue since @monajalal  has contacted us via email. feel free to open it if you have other questions.
